[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "forge-std=lib/forge-std/src",
    "@safe/contracts=lib/safe-contracts/contracts",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts",
]
gas-price = 3000000000
block-base-fee-per-gas = 3000000000

fs_permissions = [{ access = "read", path = "./" }]

solc_version = "0.8.26"
evm_version = "paris"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
